# Generated by Django 5.1.7 on 2025-04-06 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=40)),
                ('pauta', models.TextField()),
                ('average', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_visto', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('T1', 'Une palabras'), ('T2', 'Escritura'), ('T3', 'Correcion')], default='Escritura', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catedra', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_visto', models.DateField(auto_now_add=True)),
                ('fk_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.contenido')),
                ('fk_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.materia'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('fk_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.clase')),
                ('fk_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('nivel', models.CharField(choices=[('F', 'Facil'), ('M', 'Medio'), ('D', 'Dificil')], default='Medio', max_length=2)),
                ('fk_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.materia')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fk_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.pregunta'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='fk_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.profesor'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('condicion', models.BooleanField(default=True)),
                ('fk_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fk_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.respuesta'),
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('average', models.IntegerField()),
                ('fk_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.clase')),
                ('fk_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.estudiante')),
                ('fk_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.profesor')),
                ('fk_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.seccion')),
            ],
        ),
    ]
