# Generated by Django 5.1.4 on 2025-01-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_seccion_rename_fvisto_evaluacion_f_visto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='Respuesta',
            new_name='respuesta',
        ),
    ]
