# Generated by Django 5.0.8 on 2024-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('FNacimiento', models.DateField()),
                ('FRegistro', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False)),
            ],
        ),
    ]
