# Generated by Django 5.0.8 on 2024-12-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='FNacimiento',
            new_name='f_nacimiento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FRegistro',
            new_name='f_registro',
        ),
    ]
