# Generated by Django 5.2.1 on 2025-07-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('I', 'Periodo I'), ('II', 'Periodo II')], default='I', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('DOC', 'Documento'), ('VID', 'Video'), ('LNK', 'Enlace'), ('PPT', 'Presentación')], default='DOC', max_length=3)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
